import type { Metadata } from "next";
import "./globals.css";
import { Navbar, PromotionSign } from "@/components";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <PromotionSign />
        <Navbar />
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
