import type { Metadata } from "next";
import "./globals.css";
import { notFound } from 'next/navigation'
import { Footer, Navbar, PromotionSign } from "@/components";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  console.log(notFound)
  return (
    <html lang="en">
      <body>
        <PromotionSign />
        <Navbar />
        <main>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
